export const questions = [
  // ===== SCIENCE (12 questions) =====
  {
    id: 'sci-1',
    category: 'Science',
    difficulty: 'easy',
    question: 'What is the chemical symbol for gold?',
    options: ['Au', 'Ag', 'Go', 'Gd'],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'sci-2',
    category: 'Science',
    difficulty: 'easy',
    question: 'What planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-3',
    category: 'Science',
    difficulty: 'medium',
    question: 'How many bones are in the adult human body?',
    options: ['186', '206', '226', '256'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-4',
    category: 'Science',
    difficulty: 'medium',
    question: 'What is the speed of light in a vacuum (km/s)?',
    options: ['~150,000', '~300,000', '~450,000', '~600,000'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-5',
    category: 'Science',
    difficulty: 'hard',
    question: 'Which element has the highest melting point?',
    options: ['Tungsten', 'Titanium', 'Platinum', 'Carbon'],
    correctIndex: 3,
    timeLimit: 35,
  },
  {
    id: 'sci-6',
    category: 'Science',
    difficulty: 'hard',
    question: 'What is the powerhouse of the cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'sci-7',
    category: 'Science',
    difficulty: 'easy',
    question: 'What gas do plants absorb from the atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-8',
    category: 'Science',
    difficulty: 'hard',
    question: 'What is the half-life of Carbon-14?',
    options: ['2,730 years', '5,730 years', '11,460 years', '1,250 years'],
    correctIndex: 1,
    timeLimit: 40,
  },
  {
    id: 'sci-9',
    category: 'Science',
    difficulty: 'medium',
    question: 'Which vitamin is produced by the body when exposed to sunlight?',
    options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin E'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-10',
    category: 'Science',
    difficulty: 'easy',
    question: 'What is H2O more commonly known as?',
    options: ['Hydrogen peroxide', 'Water', 'Helium dioxide', 'Hydrochloric acid'],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-11',
    category: 'Science',
    difficulty: 'medium',
    question: 'What type of bond involves the sharing of electron pairs?',
    options: ['Ionic bond', 'Metallic bond', 'Covalent bond', 'Hydrogen bond'],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-12',
    category: 'Science',
    difficulty: 'hard',
    question: 'What is the most abundant element in the universe?',
    options: ['Oxygen', 'Carbon', 'Helium', 'Hydrogen'],
    correctIndex: 3,
    timeLimit: 30,
  },

  // ===== HISTORY (12 questions) =====
  {
    id: 'his-1',
    category: 'History',
    difficulty: 'easy',
    question: 'In which year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'his-2',
    category: 'History',
    difficulty: 'medium',
    question: 'Who was the first Emperor of China?',
    options: ['Liu Bang', 'Qin Shi Huang', 'Sun Tzu', 'Confucius'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'his-3',
    category: 'History',
    difficulty: 'hard',
    question: 'The Treaty of Versailles was signed in which year?',
    options: ['1917', '1918', '1919', '1920'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'his-4',
    category: 'History',
    difficulty: 'easy',
    question: 'Who discovered America in 1492?',
    options: ['Vasco da Gama', 'Ferdinand Magellan', 'Christopher Columbus', 'Amerigo Vespucci'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'his-5',
    category: 'History',
    difficulty: 'medium',
    question: 'The French Revolution began in which year?',
    options: ['1776', '1789', '1799', '1804'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'his-6',
    category: 'History',
    difficulty: 'hard',
    question: 'Which ancient civilization built Machu Picchu?',
    options: ['Aztec', 'Maya', 'Inca', 'Olmec'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'his-7',
    category: 'History',
    difficulty: 'easy',
    question: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'his-8',
    category: 'History',
    difficulty: 'medium',
    question: 'The Berlin Wall fell in which year?',
    options: ['1987', '1988', '1989', '1990'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'his-9',
    category: 'History',
    difficulty: 'hard',
    question: 'Which empire was ruled by Mansa Musa, often called the wealthiest person in history?',
    options: ['Songhai Empire', 'Mali Empire', 'Ghana Empire', 'Ethiopian Empire'],
    correctIndex: 1,
    timeLimit: 40,
  },
  {
    id: 'his-10',
    category: 'History',
    difficulty: 'easy',
    question: 'The Great Wall of China was primarily built to protect against which group?',
    options: ['Mongols', 'Japanese', 'Koreans', 'Persians'],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'his-11',
    category: 'History',
    difficulty: 'medium',
    question: 'What ship sank in 1912 after hitting an iceberg?',
    options: ['Lusitania', 'Britannic', 'Olympic', 'Titanic'],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'his-12',
    category: 'History',
    difficulty: 'hard',
    question: 'Who was the pharaoh during the Exodus according to many scholars?',
    options: ['Tutankhamun', 'Ramesses II', 'Akhenaten', 'Cleopatra VII'],
    correctIndex: 1,
    timeLimit: 35,
  },

  // ===== GEOGRAPHY (12 questions) =====
  {
    id: 'geo-1',
    category: 'Geography',
    difficulty: 'easy',
    question: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'geo-2',
    category: 'Geography',
    difficulty: 'medium',
    question: 'Which country has the longest coastline in the world?',
    options: ['Australia', 'Russia', 'Canada', 'Indonesia'],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'geo-3',
    category: 'Geography',
    difficulty: 'hard',
    question: 'What is the deepest point in the Earth\'s oceans?',
    options: ['Tonga Trench', 'Mariana Trench', 'Java Trench', 'Puerto Rico Trench'],
    correctIndex: 1,
    timeLimit: 30,
  },
  {
    id: 'geo-4',
    category: 'Geography',
    difficulty: 'easy',
    question: 'Which is the largest continent by area?',
    options: ['Africa', 'North America', 'Asia', 'Europe'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'geo-5',
    category: 'Geography',
    difficulty: 'medium',
    question: 'How many countries are there in Africa?',
    options: ['48', '54', '60', '42'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'geo-6',
    category: 'Geography',
    difficulty: 'hard',
    question: 'Which country has the most time zones?',
    options: ['Russia', 'United States', 'France', 'United Kingdom'],
    correctIndex: 2,
    timeLimit: 35,
  },
  {
    id: 'geo-7',
    category: 'Geography',
    difficulty: 'easy',
    question: 'What is the largest desert in the world?',
    options: ['Sahara', 'Arabian', 'Gobi', 'Antarctica'],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'geo-8',
    category: 'Geography',
    difficulty: 'medium',
    question: 'The Suez Canal connects the Mediterranean Sea to which body of water?',
    options: ['Black Sea', 'Red Sea', 'Arabian Sea', 'Caspian Sea'],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'geo-9',
    category: 'Geography',
    difficulty: 'hard',
    question: 'Which country is both in Europe and Asia?',
    options: ['Greece', 'Egypt', 'Turkey', 'Iran'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'geo-10',
    category: 'Geography',
    difficulty: 'easy',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'geo-11',
    category: 'Geography',
    difficulty: 'medium',
    question: 'Which river is the longest in the world?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'geo-12',
    category: 'Geography',
    difficulty: 'hard',
    question: 'What is the smallest country in the world by area?',
    options: ['Monaco', 'Nauru', 'Vatican City', 'San Marino'],
    correctIndex: 2,
    timeLimit: 30,
  },

  // ===== TECHNOLOGY (12 questions) =====
  {
    id: 'tec-1',
    category: 'Technology',
    difficulty: 'easy',
    question: 'Who co-founded Apple Computer?',
    options: ['Bill Gates', 'Steve Jobs', 'Jeff Bezos', 'Mark Zuckerberg'],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'tec-2',
    category: 'Technology',
    difficulty: 'medium',
    question: 'What does "HTTP" stand for?',
    options: [
      'HyperText Transfer Protocol',
      'High Tech Transfer Protocol',
      'HyperText Transmission Path',
      'High Traffic Transfer Protocol',
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'tec-3',
    category: 'Technology',
    difficulty: 'hard',
    question: 'In what year was the World Wide Web invented?',
    options: ['1985', '1989', '1991', '1993'],
    correctIndex: 1,
    timeLimit: 35,
  },
  {
    id: 'tec-4',
    category: 'Technology',
    difficulty: 'easy',
    question: 'What programming language was created by Brendan Eich in 10 days?',
    options: ['Python', 'Java', 'JavaScript', 'Ruby'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'tec-5',
    category: 'Technology',
    difficulty: 'medium',
    question: 'What company developed the Android mobile operating system?',
    options: ['Apple', 'Microsoft', 'Google', 'Samsung'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'tec-6',
    category: 'Technology',
    difficulty: 'hard',
    question: 'What is the name of the first electronic general-purpose computer?',
    options: ['ENIAC', 'UNIVAC', 'EDVAC', 'Colossus'],
    correctIndex: 0,
    timeLimit: 40,
  },
  {
    id: 'tec-7',
    category: 'Technology',
    difficulty: 'easy',
    question: 'What does "CPU" stand for?',
    options: [
      'Central Processing Unit',
      'Computer Personal Unit',
      'Central Program Utility',
      'Core Processing Unit',
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'tec-8',
    category: 'Technology',
    difficulty: 'medium',
    question: 'Which company created the Java programming language?',
    options: ['Microsoft', 'IBM', 'Sun Microsystems', 'Oracle'],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'tec-9',
    category: 'Technology',
    difficulty: 'hard',
    question: 'What is the base of the hexadecimal number system?',
    options: ['8', '12', '16', '24'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'tec-10',
    category: 'Technology',
    difficulty: 'easy',
    question: 'What social media platform was founded by Mark Zuckerberg?',
    options: ['Twitter', 'Instagram', 'Facebook', 'Snapchat'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'tec-11',
    category: 'Technology',
    difficulty: 'medium',
    question: 'What does "SQL" stand for?',
    options: [
      'Structured Query Language',
      'Simple Query Language',
      'Standard Question Language',
      'Sequential Query Logic',
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'tec-12',
    category: 'Technology',
    difficulty: 'hard',
    question: 'What year was the first iPhone released?',
    options: ['2005', '2006', '2007', '2008'],
    correctIndex: 2,
    timeLimit: 30,
  },

  // ===== POP CULTURE (12 questions) =====
  {
    id: 'pop-1',
    category: 'Pop Culture',
    difficulty: 'easy',
    question: 'Which band performed at the first Live Aid?',
    options: ['The Rolling Stones', 'Queen', 'U2', 'Led Zeppelin'],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'pop-2',
    category: 'Pop Culture',
    difficulty: 'medium',
    question: 'What is the highest-grossing film of all time (unadjusted)?',
    options: ['Avengers: Endgame', 'Avatar', 'Titanic', 'Star Wars: The Force Awakens'],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'pop-3',
    category: 'Pop Culture',
    difficulty: 'hard',
    question: 'Who wrote the novel "1984"?',
    options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'],
    correctIndex: 1,
    timeLimit: 30,
  },
  {
    id: 'pop-4',
    category: 'Pop Culture',
    difficulty: 'easy',
    question: 'What is the name of Harry Potter\'s school?',
    options: ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny'],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'pop-5',
    category: 'Pop Culture',
    difficulty: 'medium',
    question: 'Which artist painted the Mona Lisa?',
    options: ['Michelangelo', 'Raphael', 'Donatello', 'Leonardo da Vinci'],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'pop-6',
    category: 'Pop Culture',
    difficulty: 'hard',
    question: 'What year was the first episode of "The Simpsons" aired?',
    options: ['1987', '1988', '1989', '1990'],
    correctIndex: 2,
    timeLimit: 35,
  },
  {
    id: 'pop-7',
    category: 'Pop Culture',
    difficulty: 'easy',
    question: 'What is the best-selling music album of all time?',
    options: ['Back in Black', 'The Dark Side of the Moon', 'Thriller', 'Rumours'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'pop-8',
    category: 'Pop Culture',
    difficulty: 'medium',
    question: 'Who directed the film "Jurassic Park"?',
    options: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'George Lucas'],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'pop-9',
    category: 'Pop Culture',
    difficulty: 'hard',
    question: 'Which American author wrote "The Great Gatsby"?',
    options: ['Ernest Hemingway', 'John Steinbeck', 'F. Scott Fitzgerald', 'William Faulkner'],
    correctIndex: 2,
    timeLimit: 30,
  },
  {
    id: 'pop-10',
    category: 'Pop Culture',
    difficulty: 'easy',
    question: 'What is the name of the fictional country in "Black Panther"?',
    options: ['Zamunda', 'Wakanda', 'Genovia', 'Latveria'],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'pop-11',
    category: 'Pop Culture',
    difficulty: 'medium',
    question: 'Which band released the album "Nevermind" in 1991?',
    options: ['Pearl Jam', 'Soundgarden', 'Nirvana', 'Alice in Chains'],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'pop-12',
    category: 'Pop Culture',
    difficulty: 'hard',
    question: 'What is the name of the play within the play in Shakespeare\'s "Hamlet"?',
    options: [
      'The Death of Gonzago',
      'The Murder of Gonzago',
      'The Spanish Tragedy',
      'The Mouse-trap',
    ],
    correctIndex: 1,
    timeLimit: 45,
  },
];
